# Skipping test because rails 5.1.0 generates with an old version of capybara
rails_options:
  - "--skip-test"
  - "<%= '--skip-listen' if ENV.fetch('RAILS_VERSION', '') < '5.0' %>"
  - "--skip-javascript"
  - "<%= '--skip-webpack-install' if ENV['RAILS_SPROCKETS'] == 'true' %>"
  - "--skip-sprockets"
