rails_options:
  - "<%= '--skip-javascript' if ENV.fetch('RAILS_VERSION', '') < '6.0' && ENV['RAILS_SPROCKETS'] != 'true' %>"
  - "<%= '--skip-sprockets' if ENV['RAILS_SPROCKETS'] != 'true' %>"
  - "--skip-test"
  - "<%= '--skip-turbolinks' if ENV['RAILS_TURBOLINKS'] != 'true' %>"
  - "<%= '--skip-webpack-install' if ENV['RAILS_SPROCKETS'] == 'true' %>"
  - "<%= '--webpack' if ENV.fetch('RAILS_VERSION', '') < '6.0' && ENV['RAILS_SPROCKETS'] != 'true' %>"
