inherit_from: .rubocop_todo.yml
inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'

Rails:
  Enabled: true
Rails/FilePath:
  Exclude:
    - 'lib/generators/browse_everything/config_generator.rb'
Rails/HttpPositionalArguments:
  Exclude:
    - 'spec/controllers/browse_everything_controller_spec.rb'

Metrics/ClassLength:
  Max: 130
  Exclude:
    - 'lib/browse_everything/driver/google_drive.rb'
Metrics/LineLength:
  Max: 400
  Exclude:
    - 'spec/lib/browse_everything/driver/box_spec.rb'
    - 'spec/lib/browse_everything/driver/dropbox_spec.rb'
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Layout/IndentationConsistency:
  EnforcedStyle: rails

Naming/FileName:
  Exclude:
    - 'browse-everything.gemspec'
    - 'Gemfile'
    - 'lib/browse-everything.rb'

Style/MixinUsage:
  Exclude:
    - 'spec/lib/browse_everything/driver/s3_spec.rb'
    - 'spec/lib/browse_everything/driver/google_drive_spec.rb'
    - 'spec/lib/browse_everything/driver/file_system_spec.rb'
    - 'spec/lib/browse_everything/driver/dropbox_spec.rb'
    - 'spec/lib/browse_everything/driver/box_spec.rb'
    - 'spec/lib/browse_everything/driver/base_spec.rb'
    - 'spec/lib/browse_everything/browser_spec.rb'
    - 'spec/services/browser_factory_spec.rb'
    - 'spec/helper/browse_everything_controller_helper_spec.rb'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'
