---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
executors:
  ruby:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/browse-everything
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

jobs:
  build:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
      rails_version:
        type: string
        default: '5.2.3'
      bundler_version:
        type: string
        default: '2.0.1'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout

      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-{{ checksum "browse-everything.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "lib/generators/browse_everything/install_generator.rb" }}-{{ checksum "lib/generators/browse_everything/config_generator.rb" }}--<< parameters.rails_version >>-<< parameters.ruby_version >>

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: 'browse-everything'

      - samvera/rubocop

      - run:
          name: Install Karma for JavaScript and functional tests
          command: sudo npm install -g karma karma-jasmine karma-chrome-launcher

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - build:
          name: "ruby2-6_rails5-2"
          ruby_version: 2.6.3
      - build:
          name: "ruby2-6_rails5-1"
          ruby_version: 2.6.3
          rails_version: 5.1.7
      - build:
          name: "ruby2-5_rails5-2"
          ruby_version: 2.5.5
      - build:
          name: "ruby2-5_rails5-1"
          ruby_version: 2.5.5
          rails_version: 5.1.7
      - build:
          name: "ruby2-4_rails5-2"
          ruby_version: 2.4.6
      - build:
          name: "ruby2-4_rails5-1"
          ruby_version: 2.4.6
          rails_version: 5.1.7
